# Generated by Django 6.1.1 on 2026-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Our Story', max_length=100)),
                ('title', models.CharField(default='Every Flavor Tells a Story', max_length=150)),
                ('text', models.TextField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.')),
                ('call_phone', models.CharField(default='+80 (400) 123 4567', max_length=30)),
                ('call_phone_link', models.CharField(default='+804001234567', max_length=30)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(help_text="e.g. 'Food, Flavour'", max_length=100)),
                ('image', models.ImageField(upload_to='events/')),
                ('date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='features/')),
                ('text', models.CharField(default='Lorem Ipsum is simply dummy printing and typesetting.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(help_text="Small text above the title, e.g. 'Traditional & Hygiene'", max_length=100)),
                ('title_line_1', models.CharField(max_length=100)),
                ('title_line_2', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(default='Come with family & feel the joy of mouthwatering food', max_length=255)),
                ('button_text', models.CharField(default='View Our Menu', max_length=50)),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menu/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('badge', models.CharField(blank=True, choices=[('', 'No badge'), ('New', 'New'), ('Seasonal', 'Seasonal'), ('Hot', 'Hot')], default='', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('persons', models.CharField(max_length=20)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='service/')),
                ('link_text', models.CharField(default='View Menu', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Flavors For Royalty', max_length=100)),
                ('title', models.CharField(default='We Offer Top Notch', max_length=150)),
                ('text', models.TextField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.')),
            ],
            options={
                'verbose_name': 'Service Section (heading)',
                'verbose_name_plural': 'Service Section (heading)',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Grilli', max_length=100)),
                ('tagline', models.CharField(default='Amazing & Delicious Food', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('address', models.CharField(default='Restaurant St, Delicious City, London 9578, UK', max_length=255)),
                ('open_hours', models.CharField(default='Daily : 8.00 am to 10.00 pm', max_length=100)),
                ('phone', models.CharField(default='+1 123 456 7890', max_length=30)),
                ('phone_link', models.CharField(default='+11234567890', help_text='Digits only, used for tel: link', max_length=30)),
                ('email', models.EmailField(default='booking@restaurant.com', max_length=254)),
                ('navbar_open_hours', models.CharField(default='Open: 9.30 am - 2.30pm', max_length=100)),
                ('booking_phone', models.CharField(default='+88-123-123456', max_length=30)),
                ('booking_phone_link', models.CharField(default='+88123123456', max_length=30)),
                ('reservation_lunch_time', models.CharField(default='Monday to Sunday, 11.00 am - 2.30pm', max_length=100)),
                ('reservation_dinner_time', models.CharField(default='Monday to Sunday, 05.00 pm - 10.00pm', max_length=100)),
                ('footer_background', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_open_hours', models.CharField(default='Open : 09:00 am - 01:00 pm', max_length=100)),
                ('newsletter_offer_text', models.CharField(default='Subscribe us & Get 25% Off.', max_length=100)),
                ('copyright_text', models.CharField(default='© 2026 Grilli. All Rights Reserved', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Facebook, Instagram', max_length=50)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Special Dish', max_length=100)),
                ('title', models.CharField(default='Lobster Tortellini', max_length=150)),
                ('text', models.TextField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.')),
                ('old_price', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('new_price', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='special-dish/')),
            ],
            options={
                'verbose_name': 'Special Dish',
                'verbose_name_plural': 'Special Dish',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
