# Generated by Django 5.1.4 on 2026-09-03 17:22

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='banner_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='banner_video',
            field=models.FileField(blank=True, help_text='MP4, WebM, or OGG. Maximum size: 50 MB.', null=True, upload_to='about/videos/', validators=[website.models.validate_video_upload]),
        ),
        migrations.AddField(
            model_name='event',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, help_text='MP4, WebM, or OGG. Maximum size: 50 MB.', null=True, upload_to='events/videos/', validators=[website.models.validate_video_upload]),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='MP4, WebM, or OGG. Maximum size: 50 MB.', null=True, upload_to='hero/videos/', validators=[website.models.validate_video_upload]),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='video',
            field=models.FileField(blank=True, help_text='MP4, WebM, or OGG. Maximum size: 50 MB.', null=True, upload_to='service/videos/', validators=[website.models.validate_video_upload]),
        ),
        migrations.AddField(
            model_name='specialdish',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='specialdish',
            name='video',
            field=models.FileField(blank=True, help_text='MP4, WebM, or OGG. Maximum size: 50 MB.', null=True, upload_to='special-dish/videos/', validators=[website.models.validate_video_upload]),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='background_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='background_video',
            field=models.FileField(blank=True, help_text='MP4, WebM, or OGG. Maximum size: 50 MB.', null=True, upload_to='testimonials/videos/', validators=[website.models.validate_video_upload]),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
