# Generated by Django 5.1.4 on 2026-09-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutsection_banner_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecard',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='specialdish',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='specialdish',
            name='old_price',
        ),
    ]
