# Generated by Django 5.1.4 on 2026-09-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_servicecard_link_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
