# Generated by Django 5.1.4 on 2026-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(blank=True, help_text='Items with the same category appear together under one heading, e.g. Bikes & Rides, Food & Coffee, Café Vibes.', max_length=80),
        ),
    ]
