# Generated by Django 5.1.4 on 2026-09-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_galleryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 Torque Tales. All Rights Reserved', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Torque Tales', max_length=100),
        ),
    ]
